apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: digitalprof-ingress
  labels:
    app: digitalprof-backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: digitalprof.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: digitalprof-backend
                port:
                  number: 8080
